# Generated by Django 4.1.7 on 2023-03-06 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parent_user',
            field=models.ForeignKey(blank=True, help_text='Only populate for subuser', limit_choices_to={'account_type__in': ['user', 'administrator']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Parent User'),
        ),
    ]
