# Generated by Django 4.1.7 on 2023-03-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_number_verified',
            field=models.BooleanField(default=False, verbose_name='Phone Number Verified?'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(blank=True, default='547442eb43148293e6d844fa8eb669d8', editable=False, max_length=100, verbose_name='Token'),
        ),
    ]
